# homebrew applications
applications:
  - git
  - go
  - terraform

# homebrew cask applications
cask_applications:
  - google-chrome
  - slack
  - iterm2
  - caffeine
  - docker
  - vagrant
  - alfred
  - virtualbox
  - spotify