- hosts: local
  connection: local

  tasks:
  - command: sudo hash
  
  - name: Allow Touch ID for sudo
    lineinfile:
      path: /etc/pam.d/sudo
      insertbefore: BOF
      line: 'auth sufficient pam_tid.so'
    become: true

  - name: update homebrew
    homebrew:
      state: latest
      update_homebrew: yes

  - name: install brews
    homebrew:
      name: "{{item}}"
      state: latest
    with_items: "{{applications}}"

  - name: install casks
    homebrew_cask:
      name: "{{item}}"
      state: installed 
    with_items: "{{cask_applications}}"